sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/centos
  - secure: UFXAb5PZtsSK/l3TKVapmvZWCslrAJWAvE5hc/ogxVJhRlLG3U3ovt+3xZmfkkFlNLi8Hk5N7RVvpqGZzo7p/o8gRhJYbFM4zQ3HYLS1G1rL0p9dlod9Qq0PQHuzE2Qhl6SIT2cjLdUpLqVU4iAGAzhze+SadeOPrh6qlr62pZ+3iOMpia6TBsdgBIzuf3afsmmqNeGBdmBQ/Wqy2l+p/8NCHwVXQMe9o+nrxpaAn6ceoG6gRpAZBqrcymD/hV0texrhTbFcNXhyo5p1hTUHMeQMH1I0QJMGOBJ+p6LQ3sur/xSvH40J7WTEte/3vwDflPYaFeJuhzy/twrGhUoYl1d3geV9q+4aLkhLngAmUi8emmlO4HuvHo/De59qOwr2bDgGsBDh/yOSwmFPi4Wuqe4w8y4Tukwh2A9wM4CWGd03ZrpF8/LmMYTvAg9aimSNreZiRA8Z80aOXS9f46jbjZ/Ywk120ZuAHUw00MBEi2sg/VXyiWBr3pQLv4YOyB9uj7YbPntB+Tu4pnnXduFje836h9X5si4g7PZ9vzmX5UfV/eXZMlr1vgeLgrVdulUcaLwCIYK7VN3Rwas1wGZWhrY7Gc25Z2+tOWWX4qJIwULwbjoL4E9F3noamNqE0fjML8Une3LmMhn1FahuOdlgFWCuz1g/2uaprfkxk6lCTgk=
  - secure: d64ND1Tj700AlVboCseM3+jXFroWx31FzATyRTSBAkHtfODzYt37ph6T9SwfZthbXEnLhK/1u40inUyrXb5HPIGgo5/598KDn1DPRbOcrqp0ZNXHJERItAOykSajrQKEuoohV1ZfSApiXjq2bBQEDh5LAkA9iDjBPyLTCW0O5TUDUoH2nR4qrDmNidLBplDNfKeu41XjhHoCK9tjyE57hjtmNq3Bd9tfpMOTjtBlzUO6UbBSjm2QzD+E2trkSRXw3CYSB4SnN1lc4uN0Wc47SGdnUZBQ+SpK5aHd8BSApiAAnN3gcztCRXY7DM6B1GfdwjkCZ/r+nvnEmSzxZRt4fI8/jVI9LCmHmah2NdcXU8RDGWNsFbg2FTQpLnY4uRp3g+zbNJGEvIOjrdfvXabKAF/z2l4Zm4Q9qxvoNDRGeVxeAYnSd/CNoevZ2zE5A85fWqSAT9Do9KKZ9jYwI5QNZqAovbpEFkdlEf/ldKKNnHDWus48oh79odViHJFRTQNq6Ve1D3328GXcAUxY5vzUircR+fzEhaewo/GgiPXVzsu0EF7Nn+BUZX9cUTsXCAOiLLfm0F9+l72vZCJleaXG+h8Jz+iG6Pda35ugZUm3KwwqkqdcTjsoCTS0UWndpbJ1juiLeAAi8rS2CtxE73fiPXpBaQGJ8xy+epYAwAojhZI=
script:
- export TAG="6"
- export REPO=dairyd/centos
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG; fi
- docker push $REPO:$TAG
