sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/centos
  - secure: d7WwYLr9zMNR7yJgH9WweHhVjJMjM1wKXSBFjYYr6kOB+OmGzfBDoLviPi3rya4OJTEnDKsK5h0Gd+x2bbU464jqiyuv53bQrtrxFAORB3K8guyrxwJMwVkIVuQlefz+XeB8hKEhDtoN/Mkru2pNEG5vBgWs9PKW8JwBslZe99pORiiGdf8FdHYvYN29KAXddDcXSPYOAZFATswKIq+YzZlvt8iFcI+45xBcnAJ709CJTKs1QRopbT6wu0dGx2e1I8hgJcDTY9DPTer2qgNjIHCpTB8cyXYJRqTXdjQovOyewOiGlem7TAXXvmx43jcunEMQC6yy90U4LOK9w8ck3a4YjtNA8Ehze4RxQyRj/8PGoEQRvzORuu9fOYz4aMtu12JpzD1NsJ+8gD4RywCp6KDfRAb/kzKEcTNrYhNrgBCJgu8wH8fqA0IJ018myVFHlp0lkwMI66gBwJntAoN2GNgx5OnM/vT8nb3u9qaRPLbSutjoZvIPW6TX3WVma76uqt3moYN4GHLqkLyzlhMPXWoT6pm9u9hyB8nCAsa15EVSmFjg2cAZUNOAaugcED7CGMcv8nj7PoSSG1U6+z1qeLnZToD+PcAC87gnoKvAPNLqix/OIiS50KyPto3S5XkrgP/CkTbIZa+U/s8Dyra0JS5kgxFUPl1hpWbgQ5o8Wzc=
  - secure: i1WcmZ/7gagO7xZcuElWA8ci5j9tREucUcht6rvchjgqiyhuz0NlWB493xGDVJoTD5vcdlJ2e5itwMPL+0yNogXhPh4o9u0UpI+YU/NvLwJODH0Wdnd5PQHHx1OO91vQhsi8cCHgsfnrMLArJ7V3PH0I2vYLOqlnyj4JQAneV7x5nDOkVgohj3hebRviAaLWZK4z25SQkUbmCdXhkRHpqSUZVN81l+NwU5NiV6W8qQ6Ua0h1cO4pnrcqsKOyCXZYJbPDHuaGWzq5N1BnYCPnbDr+krtFQBHltj7k6R6Hosk5wHkNenOGa9rnEl8I0AiVtDRdPOfSZmgNYlbFLelqVqd0FVoHO2V3jwV4HbHRpqgneP0K4NAqHfRaQkyFT6E3zwUOyf2ip3qOYNDaGswtelhJ2cH0kOolJ4wWk5Pk/Z0HDds72GWJarUbxRyf/WpzJz66+8oCrX0ih+5b62qGVIMqyyHL7nAASBAsXmGzmDa6jpd2XXbqNWdalt333zxYhX5//rlDAQ25fIHpCbEstFSE2LGvJ68T8wiyaKaS8ihA1HAVkHxc0D36pb69tRtrpoOU/C9zanPRHb6AchtS0lQrU3ERXUTH261V5YztVqq5W0c4fOAlFUNnUPuYNihe6qFsW8rVHtKDWxQTH/RAq3NcnQzVSCl+9o2THPaEgMw=
script:
- export TAG="7"
- export REPO=dairyd/centos
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG; fi
- docker push $REPO:$TAG
