sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/centos
  - secure: qdd5x5LJ7m/dEWDFQsgGxx2Sp8DZnB3x3ObAvD3uiqJ4nGWwUGer8jCuAeSyKpuwWkEqsZk2c2DowWt5V7hRQpcomP9RA7YRTd5VpM9Y0rPuNz0065ri02NV8fVtZKpWUYyX5aWiQc7JOaztlL1DzyNqws3qXlJyNs7xjpL+xUorRcnhxBcgSyNPQHzL9vAg5YKQHMG+f0nxl5P4j0vIVZMkYKzwyK3wBdbMyLKKQK3eVV+yhUIqWWY9SDfVAZq7FZoi/LXfJ2suppaJ1rttGE8dTQSjbHareRbI+pt1j6wJQQ+kLrS86DtfrCaSit7T0lhjajVzcsLMc+7o/Hg1QkF71BSV+r42q5PKTq5pXb+I/iZVEIXYOUwsvtNh+7FQ9uYYQxUksK4cuL5gbVjMtKQhDqVQCkoR259BpzQ8uFIjI0WoAj9h8VhS+6ElN0+8zqQ3WE1Yz6lFfwyfls+b+pJ7SIwIpZYNH9eR7TETR0wiml9ob1a6kdosl6jTtqCu20gZAtAs2DBh39IDQ+A97RYVHMVQK9ntKZgMB5hl2X6qTxHqJasHUYf2lh95Va7G+ehPkDnQ+VVLDsv+zal5OFBzadQ/CbRm7CpSrT9Hjaez+JRhkfhXekMxePfQn7+Q5NTVIMvnFEIhj33TTrJbAZNdLPdc2MZhUGJS0seCJgY=
  - secure: KbQ9UFR/Gckxm4imnEZtNSeCSroOKWdD4OdGugf3m7Bqv0QnMKmEEuvUpPDlDHexv6vrmxhUjxgs5jOu7lziJf6QSaSQlMTobLPJQPPHBls4W4yBsKQbzLTc5Strl813UsQLmw2gguo/Aujn0IeeLOp7gYhJnVEq0srwDM3Zp3msI+E4Ou8JqXjtgSCIAgUACE13YunDvcHS6oQQLRSMRkZCWEr9o5H6gSnxNVxRGw+wziZpVqGyWEoDzi7+EmXbXBnqa1szE6Cw58HVnPGwO8lKGcQcpbW/AwEeZ77mjKXlV+VHHIeWNtPDS2xM0Q5MiQQUaTHo0WGZjVKa9UeUysq7W8ASWPCCIULGkW9zXsZrbW62kb0kPWkgdG0Nm7ZIblQbqGoy0D9G+YOU+X/vq0ALZmjbbF5AdTfLG2oufisblaFY2x+Lt6El+gk3Zc+a+3PixfZMUesdlfLRF4V27/i8sDXh/T7C0Z4joh0vq4jl4g2Xz5iGoGACt5WGbz92mUwVFHst/vmymWw98mqKWySFXx8PYQs+PvC2EfRNqH8YZ9QGN6kFUOJoBU7AqIgVuQskNndlceyhYpeqCxW+beBPiugFZjTh3YLEycjNQup8QoU2io00w8upi3jhndeniDWc7IBIrWrybed/YDaTbF0za7QbcCV8g9gJycYQxUI=
  - secure: wffVV3HVAx67pCwVPXsJ0zPSdnDvojOfIjIwB/QPQvDFYFwPahSPctZlgTwAeJjCSCEozp1CDS0oioIij7A1Tyx7j8T8CEJ5j2mC3hQ/QZj0IbfCV9i46sv4S0doxOHLeeJjWj7hAoZF8QziRa7dEzveJOnPO/Q2NIG1oD/Af4TWh5o9Zf184y3N8F0y8rNCRFk9lmb+0+sOj3wqUkHepyfQhfku5ez35hU8CmjaMtmD2K3J28/LVnvp6nWfm9/p0BEz6CswT7+QJ72+gnHzf5Re9OuDbaVGMPz52SGIgZ9ryBVL4/QQk3akBMqNDgSugt6aIAx/379eKDNih4AeaTrE1U2dtqWhjSjoCAF74D4gwaXqq520jxvH5o/XnNbGkGV88TqP2cdxg3M5QeBqD1F0CcsPyjgEFDKvLPec46ivM1U2ItwmAwsHAq0nEE6dpaCcro+kkR4o4O8s0eTylPYLE0SLni9j9QG7HQWoHehx0pBAOVz+MZvr0uE1vGnbuVuSx/UEUV8EDBeulqe+5SNsD2Wuw5vuQyIo1Hw8L6vLzqpCMEHeDZ6NYeXesZTW/h6XZN3vEyafVwy0LEQSsZ6iMSitJQB6kqgGfUGhHCkU8FIlMSBWDvnhmpdCP+zvR15BXys7HuOImQpAZejaUjPAMqgtiVXi3Q9Wd94d5Wo=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "7"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=dairyd/centos
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
