sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/centos
  - secure: QqcKE44EnYWale5KhbK/csDDJdWpNeq62i4R8FmwAE3aSdO5y2ppiJvX1v5wFCqcvsezRQcOCYrWBPlnJzTeZquVpXruNg6sfZn2PwEuDlv/DDRUJWCJ/jT+C323VoeQlkU2fGPubWRIhnw5aDCQCmzM1eijUKhssDKq1Y/gVO4bpfUVaMkq8nEKcdNcexXXj91vXNd+VO1EPQaWyOptQV8AA57CewKXj7ZUSGADjUrR/KqeliYUcntcUFeLqlD1t8HtxAPpJ7SC/FjxhS/kLx5V8gcdqbc4L5WeSIz92OKB3mSY7reW0gvNGmO7709TQIRaNeWm0O00zwGdp5sXm4KxFi9JcrcM3wISiFUXmOaoIKxHGoU3IKKDSsB76RRS+ax/zs0iVxojI7+yoA69ihlyWhhZ3QevD8XaFttmKM2+BbT8B4ASRlMlCMxBWXklfamQxaer6ktNim+GivriLiLiC/tHojTP6Yc6Jq5GUN2EI8idDqKY63JdCeQM8w3IKlK/CI+rfS4KtHYrVgOTPz/CPGpYjzwJJ+wtMqN5JV2WjI/3cBemHQgSSgLyf2GrgzNnfft/UUwv4M13zMrM0UbqoZu4HRCpQ3I6FVaEu/bhOzEx51ce/dsq1XNPW3Ycprs5J9SIzEWIQYF/+my9N/Cx+0ooA5rjiWjHwVsxDyE=
  - secure: bsBlaDoLW7xJqeWOK3K+F41aGmSIvYVidjc+sSTquA3MG9XmssRAu3+JvQKVenbD0Itre4/6AFri3JbbqJnkLoVy0Le9pvJ3MBfF7qTT5cmVs9gbBg8BLf/XA1/Qs3MXMTCrJX+HfYs6Ix4XfDUREwVKpMGiMYKqU2GDkyJdU+yrOBKBpK+ST8dzh5IuzVwMC1hKDkh12wOF4nk5rYMFTmGqkgqPfmEQkahMYW07h0fCE9ebz8dYg2KajN/c9izm35Z0PUaZhTTELLTna0SnT99vg4oZzWYgJHNf4fHE4X7fpkFrQRMqq8nOzQBZmfUvXngdF1TIUd+wwLHvuS0PbUA3rNq0ujGMg3+ctC7qBw7iw4OxmtjEqlfe6pWIvxTueFiioATXNi8EsHucMUpX3RFDjciZDYOFIkwbFE37sWzpCPXVzFSu+4wcjXL80x+5BiJpIa7NTTl5bcC9UJxdU++wxOC8gbBRQzw1ROpYbbh7IT2sFrKHc8ZmEtAJOaGJ9DQKLxhkn95yV21xCRlnofRie7JbpR8s64OE/x3O8yBJ27aFBCcUUH+WDEKNgWx+i2a7hQwpSR9eNbDxXZS/yIOe8MU3YFkdoCVQMiO9SZxVLM6smokSIlOWFYHERziEB5lipxM5IsurfFaMCff5sokEWFNDniHHKt8TPpIzRgo=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "7"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=dairyd/centos
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG; fi
- docker push $REPO:$TAG
